name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        default: 'prod'


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      SSM_PREFIX: /shortix/${{ github.event.inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4



      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Environment Variables
        run: |
          echo "Fetching environment variables from SSM..."
          VITE_USER_POOL_ID=$(aws ssm get-parameter --name "${{ env.SSM_PREFIX }}/auth/user-pool-id" --query "Parameter.Value" --output text)
          VITE_CLIENT_ID=$(aws ssm get-parameter --name "${{ env.SSM_PREFIX }}/auth/client-id" --query "Parameter.Value" --output text)
          VITE_API_URL=$(aws ssm get-parameter --name "${{ env.SSM_PREFIX }}/api/url" --query "Parameter.Value" --output text)
          
          echo "VITE_USER_POOL_ID=$VITE_USER_POOL_ID" >> .env
          echo "VITE_CLIENT_ID=$VITE_CLIENT_ID" >> .env
          echo "VITE_API_URL=$VITE_API_URL" >> .env
          
          echo "Created .env file with fetched variables."

      - name: Build Web Assets
        run: npm run build




      - name: Fetch Frontend Resources
        id: fetch-resources
        run: |
          BUCKET=$(aws ssm get-parameter --name "${{ env.SSM_PREFIX }}/web/bucket-name" --query "Parameter.Value" --output text)
          DIST_ID=$(aws ssm get-parameter --name "${{ env.SSM_PREFIX }}/web/distribution-id" --query "Parameter.Value" --output text)
          echo "bucket_name=$BUCKET" >> $GITHUB_OUTPUT
          echo "dist_id=$DIST_ID" >> $GITHUB_OUTPUT

      - name: Sync to S3
        run: |
          aws s3 sync dist/ s3://${{ steps.fetch-resources.outputs.bucket_name }} --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ steps.fetch-resources.outputs.dist_id }} --paths "/*"
